apiVersion: apps/v1
kind: Deployment
metadata:
  name: docdb-sample-deployment
  labels:
    app: docdb-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docdb-sample
  template:
    metadata:
      labels:
        app: docdb-sample
    spec:
      containers:
      - name: docdb-sample
        image: 295439051676.dkr.ecr.us-east-1.amazonaws.com/dev-docdb-sample-project:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: docdb-sample-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: docdb-sample
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000